//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamPlate
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Grades
    {
        public int GradeID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<short> MidtermGrade { get; set; }
        public Nullable<short> FinalGrade { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<decimal> GPA { get; set; }
        public Nullable<bool> PassingStatus { get; set; }
    
        public virtual TBL_Classes TBL_Classes { get; set; }
        public virtual TBL_Students TBL_Students { get; set; }
    }
}
