//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamPlate
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Marks
    {
        public int MarkID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<short> MidtermMark { get; set; }
        public Nullable<short> FinalMark { get; set; }
        public Nullable<decimal> Cumulative { get; set; }
        public Nullable<bool> PassedStatus { get; set; }
    
        public virtual TBL_Classes TBL_Classes { get; set; }
        public virtual TBL_Students TBL_Students { get; set; }
    }
}
